# Generated by Django 5.2.8 on 2025-11-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('kisisel', 'Kişisel'), ('is', 'İş'), ('okul', 'Okul'), ('diger', 'Diğer')], default='diger', max_length=20),
        ),
    ]
